- hosts: all
  become: yes
  tasks:
  - name: install mysql
    apt:
      name: mysql-server
      update_cache: yes
      state: present

  - name: install apache
    apt:
      name: apache2
      update_cache: yes
      state: present
